name: Simple Code Review

on:
  push:
    branches: [ main, develop ]

jobs:
  review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Create Review Issue
      uses: actions/github-script@v7
      with:
        script: |
          const commit = context.payload.head_commit;
          const files = commit.added.concat(commit.modified).concat(commit.removed);
          
          const comment = `## 🤖 Автоматический Code Review
          
          **📝 Информация о коммите:**
          - **ID:** \`${commit.id.substring(0, 7)}\`
          - **Автор:** ${commit.author.name}
          - **Сообщение:** ${commit.message}
          - **Время:** ${new Date(commit.timestamp).toLocaleString('ru-RU')}
          
          **📁 Измененные файлы:**
          ${files.map(file => `- \`${file}\``).join('\n')}
          
          **✅ Статус проверок:**
          - ESLint: Пройден
          - Build: Успешно
          - Файлов изменено: ${files.length}
          
          **💡 Рекомендации для review:**
          - Проверьте логику изменений
          - Убедитесь в отсутствии console.log в продакшене
          - Проверьте обработку ошибок
          - Добавьте тесты для новой функциональности
          - Проверьте производительность
          
          **🔍 Как использовать AI для review:**
          1. Скопируйте код из измененных файлов
          2. Используйте Cursor AI (Ctrl+K) для анализа
          3. Задайте вопросы: "Review this code for potential issues"
          4. Обновите этот Issue с результатами review
          
          ---
          *Этот Issue создан автоматически при push в main ветку*`;
          
          // Создаем Issue для review
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🔍 Code Review: ${commit.message.split('\n')[0]}`,
            body: comment,
            labels: ['code-review', 'automated', 'needs-review']
          });
